default_language_version:
    python: python3.9

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: local
    hooks:
        - id: mypy
          name: mypy
          entry: pipenv run mypy .
          language: system
          types:
              - python
          pass_filenames: false
        - id: isort
          name: isort
          entry: pipenv run isort .
          language: system
          types:
              - python
        - id: black
          name: black
          entry: pipenv run black .
          language: system
          types:
              - python
        - id: flake8
          name: flake8
          entry: pipenv run flake8 app models tests
          language: system
          exclude: alembic
          types:
              - python
